List<List> categoryList = [
  [
    "assets/images/PopularCategories/Hills.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Parks.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Palace.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Beach.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Forest.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Waterfall.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Lake.popular.jpg",
  ],
  [
    "assets/images/PopularCategories/Museum.popular.jpg",
  ],
];
